### ISSUE TITLE
Build directory messiness

### ISSUE THREAD

**Issue by yorhodes** [IBM-Blockchain-Starter-Kit/build-lib#10]
Right now all of the scripts need to be run in the context of the build directory. We need to clean this up and standardize with the common library scripts.

**Comment by jt-nti** [comment]
A common set of scripts should be created in a new `src` directory since these will ultimately need to be tarred up and added to a tagged release (see #5) by an automated build.

For now the old scripts should remain where they are for existing toolchains.

> Right now all of the scripts need to be run in the context of the build directory

Not sure what this means?

**Comment by jt-nti** [comment]
From @yorhodes 

> right now source-ing the pipeline-***.sh runs commands, but I was thinking it might be a better pattern to run the commands elsewhere and just grab the functions that are common there
