### ISSUE TITLE
Set up automated testing framework

### ISSUE THREAD

**Issue by jt-nti** [IBM-Blockchain-Starter-Kit/build-lib#2]
The scripts here will be used to build/test/deploy end user solutions as well as introductory samples so they must be robust and reliable

Tests need to run and pass as part of a pull request to ensure that regressions are not introduced

**Comment by jt-nti** [comment]
Needs investigation but Bash Automated Testing System (Bats) seems like it could be useful for this

https://github.com/bats-core/bats-core

Would also need to mock/stub and spy on other scripts/commands that the build scripts use, and it looks like there are some Bats related options for doing that, or some other approaches we could try

Another potentially useful tool which another project in Hursley have been using recently https://www.shellcheck.net/

**Comment by jorgedr94** [comment]
@mayarobin : Let's use this user story to track this issue.

**Comment by mayarobin** [comment]
[Potential Automated Testing Mechanisms .xlsx](https://github.com/IBM-Blockchain-Starter-Kit/build-lib/files/2112277/Potential.Automated.Testing.Mechanisms.xlsx)

**Comment by mayarobin** [comment]
Here is a draft of my notes on Bats. It details how to install Bats and explains the output
[Quick BATS Guide.docx](https://github.com/IBM-Blockchain-Starter-Kit/build-lib/files/2116401/Quick.BATS.Guide.docx)

**Comment by mayarobin** [comment]
Here is an updated version of what I have so far in terms of documentation:
[Quick BATS Guide.docx](https://github.com/IBM-Blockchain-Starter-Kit/build-lib/files/2116985/Quick.BATS.Guide.docx)

**Comment by jt-nti** [comment]
There are now a few real unit tests and they run automatically in travis so I think we can close this issue
