### ISSUE TITLE
Chaincode deployment configuration

### ISSUE THREAD

**Issue by jt-nti** [IBM-Blockchain-Starter-Kit/build-lib#34]
When deploying sample chaincode to starter plan, @sstone1's prototype did not require any configuration around which channels/peers to deploy to, or worry about different organisations being involved.

To support more complex (production?) scenarios, there needs to be some means to configure the chaincode deployment. In summary (hopefully @yorhodes and @jorgedr94 can fill in the details!) the following information is likely to be required in a multi-org environment:

- channel(s)?
- whether to install?
- which org should do the instantiate/upgrade?
- other configuration?

Need to consider where this configuration should live, and how this kind of more complex (production?) scenario fits in within devops toolchains. For example:

- is checking a live configuration file into source code repositories desirable?
    - repository is/should be shared by all organisations
    - may not want to reveal configuration to other organisations/the wider world
- how much is discoverable from the /networks/{networkID}/connection_profile API?
- how does a complex (production?) deploy fit in with continuous development?
    - current pipelines do not have a staged/production split
    - should production deployment be handled by the same pipeline?
- will orgs share devops pipelines or each have their own pipeline for the same blockchain network?
    - single pipeline would require authorisation to install/instantiate for all orgs!!
    - multiple pipelines would need to coordinate instantiation once chaincode was installed on all the required peers

Apologies that this is just a bit of a brain dump for now but I wanted to get something down for discussion.

**Comment by jt-nti** [comment]
From @simonmullaney

> needs a little bit of flexibility which could be achieved with a customisable configuration file where you could specify things like:
>
> 1) Number of organisations you want in your network
> 2) Number of peers you want in each org
> 3) Number of orderers (for enterprise plan)
> 4) Names of orgs, channel and of whole business network

**Comment by simonmullaney** [comment]
It would also be good to be able to configure:

    5. Names of the cards for the different organisations, CA's and intermediate CA's

**Comment by jt-nti** [comment]
Moved to new repo
