### ISSUE TITLE
Add nodejs chaincode support

### ISSUE THREAD

**Issue by jt-nti** [IBM-Blockchain-Starter-Kit/build-lib#54]
As a nodejs developer, I want to use the starter kit to build chaincode written in the language I'm already familiar with

**Comment by erin-hughes** [comment]
Things we need to do:

- [x] Put something in the bootstrap repo, including tests :)

- [x] Add a button to the toolchain readme with the new nodejs bootstrap repo

- [x] Add tests for the nodejs build stuff

- [x] Update the build-lib test script to run tests in the bootstrap repo

**Comment by jt-nti** [comment]
Think this is all done!! Thank you!
